
services:
  mariadb:
    environment:
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-password}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-password}
    volumes:
      - ${MARIADB_DATADIR_DEV:-./datadir}:/var/lib/mysql
